<?php

namespace Kpicaza\Bundle\MetricsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalVisitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalVisitsRepository extends EntityRepository
{
}
